/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSavingsRouteImport } from './routes/_authenticated/savings'
import { Route as AuthenticatedQuestsRouteImport } from './routes/_authenticated/quests'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedFamilyRouteImport } from './routes/_authenticated/family'
import { Route as AuthenticatedExpensesRouteImport } from './routes/_authenticated/expenses'
import { Route as AuthenticatedAutomationRouteImport } from './routes/_authenticated/automation'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavingsRoute = AuthenticatedSavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuestsRoute = AuthenticatedQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFamilyRoute = AuthenticatedFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExpensesRoute = AuthenticatedExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationRoute = AuthenticatedAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quests': typeof AuthenticatedQuestsRoute
  '/savings': typeof AuthenticatedSavingsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/expenses': typeof AuthenticatedExpensesRoute
  '/family': typeof AuthenticatedFamilyRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/quests': typeof AuthenticatedQuestsRoute
  '/savings': typeof AuthenticatedSavingsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/automation': typeof AuthenticatedAutomationRoute
  '/_authenticated/expenses': typeof AuthenticatedExpensesRoute
  '/_authenticated/family': typeof AuthenticatedFamilyRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/quests': typeof AuthenticatedQuestsRoute
  '/_authenticated/savings': typeof AuthenticatedSavingsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/automation'
    | '/expenses'
    | '/family'
    | '/insights'
    | '/profile'
    | '/quests'
    | '/savings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/sitemap.xml'
    | '/automation'
    | '/expenses'
    | '/family'
    | '/insights'
    | '/profile'
    | '/quests'
    | '/savings'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/automation'
    | '/_authenticated/expenses'
    | '/_authenticated/family'
    | '/_authenticated/insights'
    | '/_authenticated/profile'
    | '/_authenticated/quests'
    | '/_authenticated/savings'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/savings': {
      id: '/_authenticated/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof AuthenticatedSavingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quests': {
      id: '/_authenticated/quests'
      path: '/quests'
      fullPath: '/quests'
      preLoaderRoute: typeof AuthenticatedQuestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/family': {
      id: '/_authenticated/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof AuthenticatedFamilyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/expenses': {
      id: '/_authenticated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthenticatedExpensesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation': {
      id: '/_authenticated/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AuthenticatedAutomationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAutomationRoute: typeof AuthenticatedAutomationRoute
  AuthenticatedExpensesRoute: typeof AuthenticatedExpensesRoute
  AuthenticatedFamilyRoute: typeof AuthenticatedFamilyRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedQuestsRoute: typeof AuthenticatedQuestsRoute
  AuthenticatedSavingsRoute: typeof AuthenticatedSavingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAutomationRoute: AuthenticatedAutomationRoute,
  AuthenticatedExpensesRoute: AuthenticatedExpensesRoute,
  AuthenticatedFamilyRoute: AuthenticatedFamilyRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedQuestsRoute: AuthenticatedQuestsRoute,
  AuthenticatedSavingsRoute: AuthenticatedSavingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
